version: '3'
services:
  mysql-container:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_AUTH_PLUGIN: mysql_native_password

    ports:
      - "3306:3306"
    networks:
      - my-network
      
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql-container

  nodejs-container:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mysql-container
    networks:
      - my-network

networks:
  my-network:
